version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/youtubedata
      - YOUTUBE_API_URL=https://www.googleapis.com/youtube/v3/search
      - GOOGLE_API_KEY=AIzaSyBMKoCvL4Dmd5fD1PP1E1rgzGNVbTJrlFw
      - SECRET_KEY=your_secret_key
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
